const ENUSStrings = {
    // General
    TypeLabel: "Type",
    FuelLabel: "Fuel",
    CloseLabel: "Close",
    LinkLabel: "Link",
    PrintLabel: "Print",
    LoadingCompaniesLabel: "Loading Companies",
    LoadingTransactionsLabel: "Loading Transactions",
    LoadingTransactionLabel: "Loading Transaction",
    LoadingRemainingBalanceLabel: "Loading Remaining Balance",
    // Home
    RemainingTransactonLabel: "Remaining Transaction",
    MakeInvoiceLabel: "Make Invoice",
    MakePaymentLabel: "Make Payment",
    AmountLabel: "Amount",
    // Company Strings
    CompanyNameLabel: "Company Name",
    CompanyPhoneLabel: "Company Phone Number",
    CompanyEmailLabel: "Company Email Address",
    CompanyAddressLabel: "Company Address",
    CompanyCityLabel: "Company City",
    CompanyCountryLabel: "Company Country",
    CompanyZipLabel: "Company Zip Code",
    IsCompanyActiveLabel: "Is this company account active?",
    SubmitCompanyLabel: "Submit Company Details",
    CompanyIsSubmittedMessage: "Company is currently processing. Please wait",
    CompanySubmissionFailedMessage: "Company submission failed. Please look at the error to the right and try submitting it again: ",
    CompanySubmissionSuccessMessage: "Company was submitted successfully",
    // Transaction Strings
    RemoveLabel: "Remove",
    InvoiceLabel: "Invoice",
    PaymentLabel: "Payment",
    ChooseCompanyLabel: "Choose a Company",
    ChooseTypeLabel: "Choose Type",
    CheckNumberLabel: "Check Number",
    CreatedDateLabel: "Created Date",
    PaymentDateLabel: "Payment Date",
    DueDateLabel: "Due Date",
    TotalLabel: "Total",
    TicketNumberLabel: "Ticket Number",
    TransactionTotalLabel: "Total in $",
    SubmitTransactionLabel: "Submit Transaction Details",
    TransactionIsSubmittedMessage: "Transaction is currently processing. Please wait",
    TransactionSubmissionFailedMessage: "Transaction submission failed. Please look at the error to the right and try submitting it again: ",
    TransactionSubmissionInvoiceDataFailedMessage: "Some invoice data couldn't be submitted. Please see specific ones below.",
    TransactionSubmissionSuccessMessage: "Transaction was submitted successfully!",
    ViewTransactionLabel: "View Transaction",
    AddInvoiceDataLabel: "Add Invoice Row",
    TransactionIsPaymentMessage: "The current transaction is a payment",
    // User Strings
    ChooseUserLabel: "Choose User",
    FirstNameLabel: "First Name",
    LastNameLabel: "Last Name",
    UserEmailLabel: "User Email",
    UserPhoneLabel: "User Phone Number",
    UsernameLabel: "Username",
    PasswordLabel: "Password",
    ConfirmPasswordLabel: "Confirm Password",
    PasswordNotMatchingLabel: "Passwords do not match",
    SubmitUserLabel: "Submit User Details",
    // Error Strings
    BlankErrorMessage: " is required",
    NumberErrorMessage: " must be a number",
    PositiveNumberErrorMessage: " must be a positive number",
    PhoneFormatErrorMessage: " must be a phone number",
    EmailFormatErrorMessage: " must be an email address",
    DateFormatErrorMessage: " must be a date"
};

export default ENUSStrings;