const ENUSStrings = {
    // General
    TypeLabel: "Type",
    FuelLabel: "Fuel",
    CloseLabel: "Close",
    LinkLabel: "Link",
    PrintLabel: "Print",
    LoadingCompaniesLabel: "Loading Companies",
    LoadingCustomersLabel: "Loading Customers",
    LoadingTransactionsLabel: "Loading Transactions",
    LoadingTransactionLabel: "Loading Transaction",
    LoadingRemainingBalanceLabel: "Loading Remaining Balance",
    // Home
    RemainingTransactonLabel: "Remaining Transaction",
    MakeInvoiceLabel: "Make Invoice",
    MakePaymentLabel: "Make Payment",
    AmountLabel: "Amount",
    // Company Strings
    CompaniesLabel: "Companies",
    AddCompanyLabel: "Add a Company",
    EditCompaniesLabel: "Edit Companies",
    CompanyNameLabel: "Company Name",
    CompanyAddressLabel: "Company Address",
    CompanyCityLabel: "Company City",
    CompanyCountryLabel: "Company Country",
    CompanyZipLabel: "Company Zip",
    // Customer Strings
    CustomersLabel: "Customers",
    AddCustomerLabel: "Add a Customer",
    EditCustomersLabel: "Edit Customers",
    CustomerNameLabel: "Customer Name",
    CustomerPhoneLabel: "Customer Phone Number",
    CustomerEmailLabel: "Customer Email Address",
    CustomerAddressLabel: "Customer Address",
    CustomerCityLabel: "Customer City",
    CustomerCountryLabel: "Customer Country",
    CustomerZipLabel: "Customer Zip Code",
    IsCustomerActiveLabel: "Is this Customer account active?",
    SubmitCustomerLabel: "Submit Customer Details",
    CustomerIsSubmittedMessage: "Customer is currently processing. Please wait",
    CustomerSubmissionFailedMessage: "Customer submission failed. Please look at the error to the right and try submitting it again: ",
    CustomerSubmissionSuccessMessage: "Customer was submitted successfully",
    // Transaction Strings
    RemoveLabel: "Remove",
    InvoiceLabel: "Invoice",
    PaymentLabel: "Payment",
    ChooseCustomerLabel: "Choose a Customer",
    ChooseTypeLabel: "Choose Type",
    CheckNumberLabel: "Check Number",
    CreatedDateLabel: "Created Date",
    PaymentDateLabel: "Payment Date",
    DueDateLabel: "Due Date",
    TotalLabel: "Total",
    TicketNumberLabel: "Ticket Number",
    TransactionTotalLabel: "Total in $",
    SubmitTransactionLabel: "Submit Transaction Details",
    TransactionIsSubmittedMessage: "Transaction is currently processing. Please wait",
    TransactionSubmissionFailedMessage: "Transaction submission failed. Please look at the error to the right and try submitting it again: ",
    TransactionSubmissionInvoiceDataFailedMessage: "Some invoice data couldn't be submitted. Please see specific ones below.",
    TransactionSubmissionSuccessMessage: "Transaction was submitted successfully!",
    ViewTransactionLabel: "View Transaction",
    AddInvoiceDataLabel: "Add Invoice Row",
    TransactionIsPaymentMessage: "The current transaction is a payment",
    // User Strings
    UsersLabel: "Users",
    AddUserLabel: "Add a User",
    EditUsersLabel: "Edit Users",
    ChooseUserLabel: "Choose User",
    FirstNameLabel: "First Name",
    LastNameLabel: "Last Name",
    UserEmailLabel: "User Email",
    UserPhoneLabel: "User Phone Number",
    UsernameLabel: "Username",
    PasswordLabel: "Password",
    ConfirmPasswordLabel: "Confirm Password",
    PasswordNotMatchingLabel: "Passwords do not match",
    SubmitUserLabel: "Submit User Details",
    // Error Strings
    BlankErrorMessage: " is required",
    NumberErrorMessage: " must be a number",
    PositiveNumberErrorMessage: " must be a positive number",
    PhoneFormatErrorMessage: " must be a phone number",
    EmailFormatErrorMessage: " must be an email address",
    DateFormatErrorMessage: " must be a date",
    NoTransactionsErrorMessage: "No transactions exist for this company",
    NoCustomersErrorMessage: "There are no customers",
    NoCompanyCustomersErrorMessage: "There are no customers for this company",
    NoCompaniesErrorMessage: "There are no companies"
};

export default ENUSStrings;