//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicer.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ENUSStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ENUSStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Invoicer.Properties.Strings.ENUSStrings", typeof(ENUSStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isAccountActive.
        /// </summary>
        public static string AccountActivePropertyLabel {
            get {
                return ResourceManager.GetString("AccountActivePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string AddressPropertyLabel {
            get {
                return ResourceManager.GetString("AddressPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is required.
        /// </summary>
        public static string BlankError {
            get {
                return ResourceManager.GetString("BlankError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkNumber.
        /// </summary>
        public static string CheckNumberPropertyLabel {
            get {
                return ResourceManager.GetString("CheckNumberPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string CityPropertyLabel {
            get {
                return ResourceManager.GetString("CityPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company was successfully added.
        /// </summary>
        public static string CompanyAddedSuccessMessage {
            get {
                return ResourceManager.GetString("CompanyAddedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company was successfully edited.
        /// </summary>
        public static string CompanyEditedSuccessMessage {
            get {
                return ResourceManager.GetString("CompanyEditedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyID.
        /// </summary>
        public static string CompanyIDLabel {
            get {
                return ResourceManager.GetString("CompanyIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string CountryPropertyLabel {
            get {
                return ResourceManager.GetString("CountryPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createdDate.
        /// </summary>
        public static string CreatedDatePropertyLabel {
            get {
                return ResourceManager.GetString("CreatedDatePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dueDate.
        /// </summary>
        public static string DueDatePropertyLabel {
            get {
                return ResourceManager.GetString("DueDatePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string EmailPropertyLabel {
            get {
                return ResourceManager.GetString("EmailPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can you forget the .
        /// </summary>
        public static string ForgotError {
            get {
                return ResourceManager.GetString("ForgotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has an issue in the data. There&apos;s possibly a zero in one of the rows..
        /// </summary>
        public static string HasAnIssueError {
            get {
                return ResourceManager.GetString("HasAnIssueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice was successfully added.
        /// </summary>
        public static string InvoiceAddedSuccessMessage {
            get {
                return ResourceManager.GetString("InvoiceAddedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoiceData.
        /// </summary>
        public static string InvoiceDataLabel {
            get {
                return ResourceManager.GetString("InvoiceDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice was successfully edited.
        /// </summary>
        public static string InvoiceEditedSuccessMessage {
            get {
                return ResourceManager.GetString("InvoiceEditedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        public static string LimitLabel {
            get {
                return ResourceManager.GetString("LimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is missing.
        /// </summary>
        public static string MissingError {
            get {
                return ResourceManager.GetString("MissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NamePropertyLabel {
            get {
                return ResourceManager.GetString("NamePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no body in the request.
        /// </summary>
        public static string NoBodyError {
            get {
                return ResourceManager.GetString("NoBodyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  must be a number.
        /// </summary>
        public static string NumberError {
            get {
                return ResourceManager.GetString("NumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        public static string OffsetLabel {
            get {
                return ResourceManager.GetString("OffsetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paymentDate.
        /// </summary>
        public static string PaymentDatePropertyLabel {
            get {
                return ResourceManager.GetString("PaymentDatePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string PhonePropertyLabel {
            get {
                return ResourceManager.GetString("PhonePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string TotalPropertyLabel {
            get {
                return ResourceManager.GetString("TotalPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transactionID.
        /// </summary>
        public static string TransactionIDLabel {
            get {
                return ResourceManager.GetString("TransactionIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string TypePropertyLabel {
            get {
                return ResourceManager.GetString("TypePropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can&apos;t be 0.
        /// </summary>
        public static string ZeroError {
            get {
                return ResourceManager.GetString("ZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip.
        /// </summary>
        public static string ZipPropertyLabel {
            get {
                return ResourceManager.GetString("ZipPropertyLabel", resourceCulture);
            }
        }
    }
}
